sudo: require

services:
    - docker

before_install:
    - docker build -t tgvaughan/travis .

script:
    - docker run tgvaughan/travis /bin/bash -c 'cd /root; ant test'

notifications:
      slack: phylodyn:GAerIdZkKLaTFYnx6twCjwVi
